name: donor_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1


  cupertino_icons: ^1.0.8
  google_fonts: ^5.0.0
  provider: ^6.1.2
  fluttertoast: ^8.0.0
  shared_preferences: ^2.2.2
  flutter_native_splash: ^2.3.7
  http: ^1.1.0
  google_maps_flutter: ">=2.5.3 <3.0.0"
  geolocator: ^9.0.2
  jwt_decoder: ^2.0.1
  image_picker: ^1.0.2
  http_parser: ^4.0.2
  dropdown_button2: ^2.3.9
  flutter_rounded_date_picker: ^3.0.1
  excel: ^2.0.4
  path_provider: ^2.0.11
  pdf: ^3.6.5
  printing: ^5.9.0
  open_file: ^3.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # Asset Images
  assets:
    - assets/images/drop.jpeg
    - assets/images/alert.png
    - assets/images/donate.png
    - assets/images/reset.png
    - assets/images/study.png
    - assets/images/urgent.jpeg
    - assets/images/donation_banner.png
    - assets/animation/ezgif.com-crop.gif
    - assets/animation/ezgif.com-resize.gif

  # Custom Fonts
  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu/Ubuntu-Regular.ttf
        - asset: fonts/Ubuntu/Ubuntu-Bold.ttf
          weight: 700
        - asset: fonts/Ubuntu/Ubuntu-Italic.ttf
          style: italic
